services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks:
      - my_app
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/data
    networks:
      - my_app
    ports:
      - 6379:6379

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    networks:
      - my_app
    ports:
      - "5540:5540"

  web:
    build: .
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: ecs_application_db
      DB_PORT: 5432
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/rails-app
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "redis"
    networks:
      - my_app

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - ./:/rails-app
    networks:
      - my_app
    environment:
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: ecs_application_db
      DB_PORT: 5432
      DB_HOST: db
    depends_on:
      - "redis"

volumes:
  db:
  bundle:
  redis:
networks:
  my_app:
